# Generated by Django 5.0.3 on 2025-04-24 11:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quoteserve', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Quote',
            new_name='PreQuote',
        ),
    ]
