# Generated by Django 5.0.1 on 2024-01-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0002_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='username',
        ),
        migrations.AddField(
            model_name='video',
            name='video_file',
            field=models.FileField(default='path/to/default_video.mp4', upload_to='videos/'),
        ),
    ]
