# Generated by Django 5.0.1 on 2024-01-16 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0004_quote'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quote',
            old_name='created_at',
            new_name='posted_date',
        ),
    ]
