# Generated by Django 5.0.1 on 2024-01-18 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userhome', '0006_imagepost'),
    ]

    operations = [
        migrations.RenameField(
            model_name='imagepost',
            old_name='img_file',
            new_name='imgfile',
        ),
    ]
